// Generated by nitro

// App Config
import type { Defu } from 'defu'



type UserAppConfig = Defu<{}, []>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}
  interface NitroRuntimeConfig {
   openhub: {
      provider: string,

      remote: boolean,

      remoteUrl: string,

      remoteSecret: string,
   },
  }
}
export {}