// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/files': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/files').default>>>>
    }
    '/api/sessions': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sessions').default>>>>
    }
    '/api/users': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users').default>>>>
    }
    '/__openhub2/proxy': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../runtimes/nitro/src/endpoint/proxy').default>>>>
    }
  }
}
export {}