packages:
  - packages/types
  - packages/providers/*
  - packages/runtimes/*
  - packages/metaframeworks/*
  - packages/examples/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - workerd
